#include <iostream>
#include <fstream>
#include <string>
#include <sstream>

using namespace std;

void printStudentInfo() {
    setlocale(LC_ALL, "ru_RU.UTF-8");
    cout << "Студент: Братерский Александр Максимович" << endl;
    cout << "Группа: М10-134БВ-25" << endl;
    cout << "Задание: task_4" << endl;
    cout << "------------------------" << endl;
}

void analyzeTextFile() {
    string filename;
    cout << "Enter the name of the text file (e.g., input.txt): ";
    cin >> filename;
    
    ifstream file(filename);
    if (!file.is_open()) {
        cout << "Error opening file: " << filename << endl;
        cout << "Please make sure the file exists in the current directory." << endl;
        return;
    }
    
    int lineCount = 0;
    int wordCount = 0;
    string line;
    
    while (getline(file, line)) {
        lineCount++;
        
        
        stringstream ss(line);
        string word;
        while (ss >> word) {
            wordCount++;
        }
    }
    file.close();
    
   
    cout << "\nFile Analysis Results:" << endl;
    cout << "======================" << endl;
    cout << "Filename: " << filename << endl;
    cout << "Total lines: " << lineCount << endl;
    cout << "Total words: " << wordCount << endl;
    
    // Запись результатов в файл report.txt
    ofstream reportFile("report.txt");
    if (!reportFile.is_open()) {
        cout << "Error creating report.txt file!" << endl;
        return;
    }
    
    reportFile << "File Analysis Report" << endl;
    reportFile << "====================" << endl;
    reportFile << "Filename: " << filename << endl;
    reportFile << "Total lines: " << lineCount << endl;
    reportFile << "Total words: " << wordCount << endl;
    reportFile << "Report generated by: John Doe, Group CS-21" << endl;
    
    reportFile.close();
    cout << "\nReport saved to report.txt" << endl;
    
   
    cout << "\nContents of report.txt:" << endl;
    cout << "======================" << endl;
    ifstream showReport("report.txt");
    string reportLine;
    while (getline(showReport, reportLine)) {
        cout << reportLine << endl;
    }
    showReport.close();
}

int main() {
    printStudentInfo();
    analyzeTextFile();
    
    return 0;
}